# Generated by Django 6.1.1 on 2026-09-23 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RascunhoGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semestre', models.CharField(db_index=True, max_length=10)),
                ('titulo', models.CharField(default='Minha Grade', max_length=100)),
                ('esta_ativa', models.BooleanField(default=True, help_text='Indica se é a grade principal do semestre em exibição')),
                ('total_creditos_planejados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rascunhos_grade', to='perfil.perfilestudante')),
            ],
            options={
                'verbose_name': 'Rascunho de Grade',
                'verbose_name_plural': 'Rascunhos de Grade',
                'db_table': 'rascunhos_grade',
            },
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='2=Segunda, 3=Terça, 4=Quarta, 5=Quinta, 6=Sexta, 7=Sábado')),
                ('turno', models.CharField(help_text='M=Manhã, T=Tarde, N=Noite', max_length=1)),
                ('slot_inicio', models.PositiveSmallIntegerField(help_text='Bloco inicial (1 a 6)')),
                ('slot_fim', models.PositiveSmallIntegerField(help_text='Bloco final (1 a 6)')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_horario', to='catalog.turma')),
            ],
            options={
                'verbose_name': 'Horário de Turma',
                'verbose_name_plural': 'Horários de Turmas',
                'db_table': 'horarios_turma',
                'indexes': [models.Index(fields=['dia_semana', 'turno', 'slot_inicio', 'slot_fim'], name='horarios_tu_dia_sem_6fe8ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cor_hex', models.CharField(default='#3B82F6', max_length=7)),
                ('esta_travada', models.BooleanField(default=False, help_text='Trava o slot visualmente no grid contra alterações acidentais')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_adicionadas', to='catalog.turma')),
                ('rascunho_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planner.rascunhograde')),
            ],
            options={
                'verbose_name': 'Item da Grade',
                'verbose_name_plural': 'Itens da Grade',
                'db_table': 'itens_grade',
                'unique_together': {('rascunho_grade', 'turma')},
            },
        ),
    ]
