# Generated by Django 6.1.1 on 2026-09-23 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True, unique=True)),
                ('tokens_simulacao', models.PositiveIntegerField(default=10)),
                ('bonus_calouro_resgatado', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carteira de Usuário',
                'verbose_name_plural': 'Carteiras de Usuários',
                'db_table': 'carteiras_usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True, unique=True)),
                ('apelido_anonimo', models.CharField(max_length=60)),
                ('sticker_avatar', models.CharField(default='capivara_alfa', max_length=50)),
                ('semestre_ingresso', models.CharField(max_length=10)),
                ('ira_calculado', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('creditos_integralizados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes_matriculados', to='catalog.cursograduacao')),
            ],
            options={
                'verbose_name': 'Perfil de Estudante',
                'verbose_name_plural': 'Perfis de Estudantes',
                'db_table': 'perfis_estudante',
            },
        ),
        migrations.CreateModel(
            name='TransacaoToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('operacao', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('bonus_calouro', 'Bônus de Calouro')], default='debito', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='perfil.carteirausuario')),
            ],
            options={
                'verbose_name': 'Transação de Token',
                'verbose_name_plural': 'Transações de Tokens',
                'db_table': 'transacoes_tokens',
            },
        ),
        migrations.CreateModel(
            name='ListaMateriasAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('cursando', 'Cursando'), ('concluida', 'Concluída')], default='planejada', max_length=15)),
                ('mencao_obtida', models.CharField(blank=True, help_text='Menção oficial: SS, MS, MM, MI, II, SR, TR', max_length=5, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_salvaram', to='catalog.materia')),
                ('perfil_estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_salvas', to='perfil.perfilestudante')),
            ],
            options={
                'verbose_name': 'Matéria Salva pelo Aluno',
                'verbose_name_plural': 'Matérias Salvas pelos Alunos',
                'db_table': 'listas_materias_aluno',
                'unique_together': {('perfil_estudante', 'materia')},
            },
        ),
    ]
