# Generated by Django 6.1.1 on 2026-09-23 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPadronizada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('categoria', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('neutra', 'Neutra')], default='neutra', max_length=10)),
            ],
            options={
                'verbose_name': 'Tag Padronizada',
                'verbose_name_plural': 'Tags Padronizadas',
                'db_table': 'tags_padronizadas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_anonimo', models.CharField(db_index=True, max_length=64)),
                ('nota_didatica', models.PositiveSmallIntegerField(help_text='Escala de 1 a 5')),
                ('nota_dificuldade', models.PositiveSmallIntegerField(help_text='Escala de 1 a 5')),
                ('mencao_obtida', models.CharField(blank=True, max_length=5, null=True)),
                ('status_aprovacao', models.CharField(default='passei', help_text='passei | reprovei | tranquei', max_length=15)),
                ('emoji_vibe', models.CharField(default='😎', max_length=10)),
                ('cobra_presenca', models.BooleanField(default=False)),
                ('avaliacao_justa', models.BooleanField(default=True)),
                ('possui_monitoria', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('status_moderacao', models.CharField(choices=[('publicada', 'Publicada'), ('em_revisao', 'Em Revisão'), ('denunciada', 'Denunciada')], default='publicada', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalog.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalog.professor')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='catalog.turma')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacoes',
            },
        ),
        migrations.CreateModel(
            name='ResumoIADocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resumo_executivo', models.TextField(help_text='Síntese de comentários gerada pelo modelo de IA')),
                ('badges', models.JSONField(default=list, help_text="Ex: ['Provas Coerentes', 'Listas Valem Nota']")),
                ('selo_padge', models.CharField(blank=True, max_length=50, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumo_ia', to='catalog.professor')),
            ],
            options={
                'verbose_name': 'Resumo de IA do Docente',
                'verbose_name_plural': 'Resumos de IA dos Docentes',
                'db_table': 'resumos_ia_docente',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoTagPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.avaliacao')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.tagpadronizada')),
            ],
            options={
                'db_table': 'avaliacoes_tags_pivot',
                'unique_together': {('avaliacao', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tags',
            field=models.ManyToManyField(related_name='avaliacoes', through='review.AvaliacaoTagPivot', to='review.tagpadronizada'),
        ),
        migrations.CreateModel(
            name='NuvemPalavras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('palavra', models.CharField(max_length=50)),
                ('frequencia', models.PositiveIntegerField(default=1)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_frequentes', to='catalog.professor')),
            ],
            options={
                'verbose_name': 'Nuvem de Palavras',
                'verbose_name_plural': 'Nuvens de Palavras',
                'db_table': 'nuvens_palavras',
                'unique_together': {('professor', 'palavra')},
            },
        ),
        migrations.CreateModel(
            name='ReacaoAvaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_reator', models.CharField(db_index=True, max_length=64)),
                ('tipo_reacao', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote'), ('denuncia', 'Denúncia')], default='upvote', max_length=10)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='review.avaliacao')),
            ],
            options={
                'db_table': 'reacoes_avaliacao',
                'unique_together': {('avaliacao', 'hash_reator')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('hash_anonimo', 'materia', 'professor')},
        ),
    ]
