# Generated by Django 6.1.1 on 2026-09-23 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamentoRU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('almoco', 'Almoço'), ('jantar', 'Jantar')], max_length=10)),
                ('dias_semana_texto', models.CharField(default='Segunda a Sexta', max_length=60)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_ru', to='catalog.campus')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento do RU',
                'verbose_name_plural': 'Horários de Funcionamento do RU',
                'db_table': 'horarios_funcionamento_ru',
            },
        ),
        migrations.CreateModel(
            name='CardapioRU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_refeicao', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('almoco', 'Almoço'), ('jantar', 'Jantar')], max_length=10)),
                ('prato_principal', models.CharField(max_length=200)),
                ('opcao_vegetariana_vegana', models.CharField(max_length=200)),
                ('guarnicao', models.CharField(max_length=200)),
                ('salada', models.CharField(max_length=200)),
                ('sobremesa', models.CharField(max_length=200)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios_ru', to='catalog.campus')),
            ],
            options={
                'verbose_name': 'Cardápio do RU',
                'verbose_name_plural': 'Cardápios do RU',
                'db_table': 'cardapios_ru',
                'unique_together': {('campus', 'data_refeicao', 'turno')},
            },
        ),
    ]
