# Generated by Django 6.1.1 on 2026-09-23 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
                'db_table': 'campi',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='catalog.campus')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='CursoGraduacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('total_creditos_obrigatorios', models.PositiveIntegerField(default=0)),
                ('total_creditos_optativos', models.PositiveIntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='catalog.departamento')),
            ],
            options={
                'verbose_name': 'Curso de Graduação',
                'verbose_name_plural': 'Cursos de Graduação',
                'db_table': 'cursos_graduacao',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_materia', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('creditos', models.PositiveIntegerField(default=4)),
                ('carga_horaria', models.PositiveIntegerField(default=60)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='catalog.departamento')),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('siape', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nome_completo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('email_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('url_foto', models.URLField(blank=True, null=True)),
                ('titulo_academico', models.CharField(blank=True, max_length=50, null=True)),
                ('url_lattes', models.URLField(blank=True, null=True)),
                ('localizacao_gabinete', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='catalog.departamento')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
            },
        ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semestre_ideal', models.PositiveSmallIntegerField()),
                ('natureza', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa')], default='obrigatoria', max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_curricular', to='catalog.cursograduacao')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes_curso', to='catalog.materia')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'db_table': 'matrizes_curriculares',
                'unique_together': {('curso', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='RequisitoMateria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_relacao', models.CharField(choices=[('pre_requisito', 'Pré-Requisito'), ('co_requisito', 'Co-Requisito'), ('equivalencia', 'Equivalência')], default='pre_requisito', max_length=20)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_origem', to='catalog.materia')),
                ('materia_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_alvo', to='catalog.materia')),
            ],
            options={
                'verbose_name': 'Requisito de Matéria',
                'verbose_name_plural': 'Requisitos de Matérias',
                'db_table': 'requisitos_materia',
                'unique_together': {('materia', 'materia_requisito', 'tipo_relacao')},
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semestre', models.CharField(db_index=True, max_length=10)),
                ('codigo_turma', models.CharField(max_length=10)),
                ('horario_bruto', models.CharField(max_length=100)),
                ('local_sala', models.CharField(blank=True, max_length=150, null=True)),
                ('vagas_ofertadas', models.PositiveIntegerField(default=0)),
                ('vagas_ocupadas', models.PositiveIntegerField(default=0)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='catalog.materia')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='catalog.professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
                'unique_together': {('materia', 'semestre', 'codigo_turma')},
            },
        ),
    ]
